# Generated by Django 6.0 on 2025-12-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alimentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("carboidratos", models.FloatField()),
                ("proteinas", models.FloatField()),
                ("gorduras", models.FloatField()),
                ("calorias", models.IntegerField()),
            ],
        ),
    ]
