# Generated by Django 6.0 on 2025-12-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contador_de_calorias", "0002_alimentoingerido"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alimentos",
            name="calorias",
        ),
    ]
